#!/usr/bin/env node
// Build a self-contained, searchable HTML catalog from registry.json.
// No server, no external assets — open catalog/index.html in any browser.
// Theme-aware (light/dark) and responsive.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { buildRegistry } from "./registry.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "catalog", "index.html");

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

function card(m) {
  const tags = m.tags.map((t) => `<span class="tag">${esc(t)}</span>`).join("");
  return `<article class="card" data-search="${esc((m.id + " " + m.name + " " + m.description + " " + m.tags.join(" ")).toLowerCase())}" data-domain="${esc(m.domain)}">
    <div class="card-head"><span class="domain domain-${esc(m.domain)}">${esc(m.domain)}</span><code class="id">${esc(m.id)}</code></div>
    <h3>${esc(m.name)}</h3>
    <p>${esc(m.description)}</p>
    <div class="tags">${tags}</div>
    <div class="run"><code>node core/cli.mjs run ${esc(m.id)} '&lt;json&gt;'</code></div>
  </article>`;
}

function page(reg) {
  const chips = ["all", ...reg.domains]
    .map((d) => `<button class="chip${d === "all" ? " active" : ""}" data-filter="${esc(d)}">${esc(d)}</button>`)
    .join("");
  return `<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>SkillForge — ${reg.count} skills</title>
<style>
:root{--bg:#fafafa;--fg:#18181b;--muted:#71717a;--card:#fff;--border:#e4e4e7;--accent:#3b7a57}
@media(prefers-color-scheme:dark){:root{--bg:#0d0d0f;--fg:#f4f4f5;--muted:#a1a1aa;--card:#18181b;--border:#27272a;--accent:#5db088}}
*{box-sizing:border-box}body{margin:0;font:15px/1.55 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--fg)}
header{padding:40px 24px 8px;max-width:1100px;margin:0 auto}
h1{margin:0;font-size:28px;letter-spacing:-.02em}h1 span{color:var(--accent)}
.sub{color:var(--muted);margin:6px 0 20px}
.controls{max-width:1100px;margin:0 auto;padding:0 24px;display:flex;flex-wrap:wrap;gap:10px;align-items:center}
input{flex:1;min-width:200px;padding:10px 14px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--fg);font-size:15px}
.chips{display:flex;flex-wrap:wrap;gap:6px}
.chip{padding:7px 13px;border:1px solid var(--border);border-radius:999px;background:var(--card);color:var(--muted);cursor:pointer;font-size:13px}
.chip.active{background:var(--accent);color:#fff;border-color:var(--accent)}
.grid{max-width:1100px;margin:20px auto;padding:0 24px;display:grid;gap:16px;grid-template-columns:repeat(auto-fill,minmax(300px,1fr))}
.card{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:18px}
.card-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}
.domain{font-size:11px;text-transform:uppercase;letter-spacing:.06em;font-weight:700;color:var(--accent)}
.id{font-size:12px;color:var(--muted)}
h3{margin:2px 0 6px;font-size:17px}p{margin:0 0 12px;color:var(--muted)}
.tags{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:12px}
.tag{font-size:11px;padding:3px 8px;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--muted)}
.run code{display:block;font-size:12px;background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:8px 10px;overflow-x:auto;white-space:nowrap}
.empty{max-width:1100px;margin:40px auto;padding:0 24px;color:var(--muted);display:none}
footer{max-width:1100px;margin:40px auto;padding:16px 24px;color:var(--muted);font-size:13px;border-top:1px solid var(--border)}
</style></head><body>
<header><h1>Skill<span>Forge</span></h1><p class="sub">${reg.count} runnable skills across ${reg.domains.length} domains. A growing capability library.</p></header>
<div class="controls"><input id="q" type="search" placeholder="Search skills, tags, descriptions…" aria-label="Search skills"><div class="chips">${chips}</div></div>
<main class="grid" id="grid">${reg.skills.map(card).join("")}</main>
<p class="empty" id="empty">No skills match your search.</p>
<footer>Generated by <code>core/build-catalog.mjs</code>. Run a skill: <code>node core/cli.mjs run &lt;id&gt; '&lt;json&gt;'</code></footer>
<script>
const q=document.getElementById('q'),grid=document.getElementById('grid'),empty=document.getElementById('empty');
let domain='all';
function apply(){const term=q.value.trim().toLowerCase();let shown=0;
  for(const c of grid.children){const okD=domain==='all'||c.dataset.domain===domain;const okT=!term||c.dataset.search.includes(term);const vis=okD&&okT;c.style.display=vis?'':'none';if(vis)shown++;}
  empty.style.display=shown?'none':'block';}
q.addEventListener('input',apply);
for(const chip of document.querySelectorAll('.chip')){chip.addEventListener('click',()=>{document.querySelector('.chip.active').classList.remove('active');chip.classList.add('active');domain=chip.dataset.filter;apply();});}
</script></body></html>`;
}

const reg = await buildRegistry();
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, page(reg));

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  console.log(`catalog written: catalog/index.html (${reg.count} skills)`);
}
