#!/usr/bin/env node
// @bamboo/tools — meta audit
//
// Statically scans every App Router route for SEO/social metadata coverage.
// No dev server or browser needed, so it runs fast and deterministically in the
// 24/7 loop and in CI. It reports gaps (missing canonical, OpenGraph, etc.) and
// writes a findings file the build loop turns into backlog tasks.
//
// Usage: node tools/audit-meta.mjs [--strict]
//   --strict  exit non-zero when any REQUIRED field is missing (for CI gating)

import { readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const APP_DIR = join(ROOT, "src", "app");
const AUDIT_OUT = join(ROOT, "docs", "audits", "meta.md");

// Fields we check for on each route. `required` gates --strict.
const CHECKS = [
  { key: "title", label: "title", required: true, re: /\btitle\s*:/ },
  { key: "description", label: "description", required: true, re: /\bdescription\s*:/ },
  { key: "canonical", label: "canonical URL", required: false, re: /\bcanonical\s*:/ },
  { key: "openGraph", label: "OpenGraph", required: false, re: /\bopenGraph\s*:/ },
  { key: "twitter", label: "Twitter card", required: false, re: /\btwitter\s*:/ },
];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/^page\.(t|j)sx?$/.test(name)) out.push(full);
  }
  return out;
}

// "src/app/privacy/page.tsx" -> "/privacy"; "src/app/page.tsx" -> "/"
function routeOf(file) {
  const rel = relative(APP_DIR, dirname(file)).replace(/\\/g, "/");
  return rel === "" ? "/" : `/${rel}`;
}

// The root layout supplies fallback metadata inherited by every route.
function layoutSource() {
  try {
    return readFileSync(join(APP_DIR, "layout.tsx"), "utf8");
  } catch {
    return "";
  }
}

function auditRoute(file, layout) {
  const src = readFileSync(file, "utf8");
  const hasOwnMetadata = /export\s+(const|async\s+function)\s+(metadata|generateMetadata)\b/.test(src);
  const findings = [];
  for (const check of CHECKS) {
    const inOwn = hasOwnMetadata && check.re.test(src);
    const inLayout = check.re.test(layout);
    if (!inOwn && !inLayout) {
      findings.push({ ...check, source: "missing" });
    } else {
      findings.push({ ...check, source: inOwn ? "route" : "layout" });
    }
  }
  return { route: routeOf(file), file: relative(ROOT, file), hasOwnMetadata, findings };
}

const layout = layoutSource();
const results = walk(APP_DIR).map((f) => auditRoute(f, layout)).sort((a, b) => a.route.localeCompare(b.route));

const missingRequired = [];
const missingOptional = [];
for (const r of results) {
  for (const f of r.findings) {
    if (f.source !== "missing") continue;
    (f.required ? missingRequired : missingOptional).push({ route: r.route, label: f.label });
  }
}

// --- Console report ---
const line = "─".repeat(52);
console.log(`\nBamboo meta audit — ${results.length} route(s)\n${line}`);
for (const r of results) {
  const cells = r.findings
    .map((f) => `${f.source === "missing" ? "✗" : f.source === "route" ? "●" : "○"} ${f.label}`)
    .join("   ");
  console.log(`${r.route.padEnd(12)} ${cells}`);
}
console.log(line);
console.log("● route-level   ○ inherited from layout   ✗ missing");
console.log(`\nRequired gaps: ${missingRequired.length}   Optional gaps: ${missingOptional.length}\n`);

// --- Findings file for the build loop ---
const md = [
  "# Meta audit findings",
  "",
  `Generated by \`tools/audit-meta.mjs\`. ${results.length} routes scanned.`,
  "",
  "## Backlog candidates",
  "",
];
if (missingRequired.length === 0 && missingOptional.length === 0) {
  md.push("- No gaps found. Every route has full metadata coverage. ✅");
} else {
  for (const m of missingRequired) md.push(`- [ ] (required) \`${m.route}\` is missing ${m.label}`);
  for (const m of missingOptional) md.push(`- [ ] (nice-to-have) \`${m.route}\` is missing ${m.label}`);
}
md.push("", "## Coverage table", "", "| Route | " + CHECKS.map((c) => c.label).join(" | ") + " |");
md.push("| --- | " + CHECKS.map(() => "---").join(" | ") + " |");
for (const r of results) {
  const cells = r.findings.map((f) => (f.source === "missing" ? "✗" : f.source === "route" ? "route" : "layout"));
  md.push(`| \`${r.route}\` | ${cells.join(" | ")} |`);
}
md.push("");
mkdirSync(dirname(AUDIT_OUT), { recursive: true });
writeFileSync(AUDIT_OUT, md.join("\n"));
console.log(`Findings written to ${relative(ROOT, AUDIT_OUT)}`);

if (process.argv.includes("--strict") && missingRequired.length > 0) {
  console.error(`\nStrict mode: ${missingRequired.length} required field(s) missing.`);
  process.exit(1);
}
